apiVersion: v1
kind: ConfigMap
metadata: {name: fastapi-config}
data:
  RW_URL: "postgresql://perripopo-service:PASS@contratos-db-cluster-rw.default.svc.cluster.local:5432/sys-gen-contracts"
  RO_URL: "postgresql://perripopo-service:PASS@contratos-db-cluster-ro.default.svc.cluster.local:5432/sys-gen-contracts"
